config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

def create
  @post = Post.new(post_params)

  if @post.save
  redirect_to @post
  else
    render 'new'
end
end

def show
  @post = Post.find(params[:id])
end

private

def post_params
  params.require(:post).permit(:title, :body)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dataplexity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div id="main_content">
  <div id="header">
    <p>All Posts</p>

    <div class="buttons">
      <button class="button"><%= link_to "New Post", new_post_path %></button>
      <button class="button">Log Out</button>
    </div>
  </div>

  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
  <% end %>

<div id="sidebar">
  <div id="logo">
    <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
    <% end %>
  </div>

  <ul>
    <li class="category">Website</li>
    <li><%= link_to "Blog", root_path %></li>
    <li>About</li>
  </ul>

  <ul>
    <li class="category">Social</li>
    <li><a> tba </a></li>
  </ul>

  <p class="sign_in">Admin Login</p>
</div>

  <%= yield %>

</div>
</body>
</html>

app/views/posts/index.erb
<h1>This is a placeholder for index.html.erb</h1>
<% @posts.each do |post| %>
    <div class="post_wrapper">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    </div>
<% end %>

app/views/posts/new.erb
<div id="page_wrapper">
    <h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
      <% if @post.errors.any? %>
          <div id="errors">
            <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_field :body %><br>
    <br>
    <%= f.submit %>
<% end %>
</div>

app/views/posts/show.erb
 <!--# Adds our title in an  tag with class of title-->
 <div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <!--# Adds the time the post was created at-->
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
  </p>

  <!--# Adds the body content-->
  <p class="body">
    <%= @post.body %>
  </p>
</div>